[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  FIREBASE_PROJECT_ID = "jonny-4d656"

[[redirects]]
  from = "/post/:id"
  to = "/.netlify/functions/post-preview?id=:id"
  status = 200
  force = true
